### ISSUE TITLE
Error OSX command line

### ISSUE THREAD

**Issue by fmarsoni** [unindented/electron-installer-debian#3]
Trying to create a deb package. After using electron-packager tried this:

```
electron-installer-debian --src ./Marinamilitare-linux-x64 --dest ./ --arch amd64

Creating package (this may take a while)

[Error: Error executing command (2): 
fakeroot dpkg-deb --build /var/folders/03/krb5m9s50479glzzw7d_h31w0000gn/T/electron-116110-5657-93rkda/marinamilitare_1.0.0_amd64
dpkg-deb: error: parsing file '/var/folders/03/krb5m9s50479glzzw7d_h31w0000gn/T/electron-116110-5657-93rkda/marinamilitare_1.0.0_amd64/DEBIAN/control' near line 9 package 'marinamilitare:amd64':
 blank line in value of field 'Installed-Size'
] 'Error: Error executing command (2): \nfakeroot dpkg-deb --build /var/folders/03/krb5m9s50479glzzw7d_h31w0000gn/T/electron-116110-5657-93rkda/marinamilitare_1.0.0_amd64\ndpkg-deb: error: parsing file \'/var/folders/03/krb5m9s50479glzzw7d_h31w0000gn/T/electron-116110-5657-93rkda/marinamilitare_1.0.0_amd64/DEBIAN/control\' near line 9 package \'marinamilitare:amd64\':\n blank line in value of field \'Installed-Size\'\n\n    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/electron-installer-debian/src/installer.js:55:23)\n    at emitTwo (events.js:100:13)\n    at ChildProcess.emit (events.js:185:7)\n    at maybeClose (internal/child_process.js:821:16)\n    at Socket.<anonymous> (internal/child_process.js:319:11)\n    at emitOne (events.js:90:13)\n    at Socket.emit (events.js:182:7)\n    at Pipe._onclose (net.js:469:12)'
```
And directory /var/folders/03/krb5m9s50479glzzw7d_h31w0000gn/T/electron-116110-5657-93rkda doesn't exists

**Comment by fmarsoni** [comment]
Problem was
description: ''
in package.json
