### ISSUE TITLE
Getting error Error executing command

### ISSUE THREAD

**Issue by prasadbe** [unindented/electron-installer-debian#80]
blank line in value of field 'Homepage'

    at ChildProcess.<anonymous> (/usr/lib/node_modules/electron-installer-debian/src/installer.js:67:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by unindented** [comment]
If you delete the template issue, I have to close the ticket, as I don't have enough information to investigate. Sorry!
