### ISSUE TITLE
Creating package (this may take a while) Error: Error executing command (2):

### ISSUE THREAD

**Issue by prasadbe** [unindented/electron-installer-debian#81]
**What version of `electron-installer-debian` are you using? **^0.5.1**

**What version of `node` and `npm` are you using?** **v7.4.0**  & **4.0.5**

**What operating system are you using?**  Linux

**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**  yes

**If not, paste here the output of the following commands:**

```
$ git clone https://github.com/unindented/electron-installer-debian.git
$ cd electron-installer-debian/example
$ DEBUG='electron-installer-debian' npm run build
```

**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
electron installer working fine ..To convert deb it throws error

**What did you expect to happen?**
deb format application expected

**What actually happened?**
while convert deb file it throws error

error detail is 
electron-installer-debian --version false  --src dist/app-linux-x64/ --dest dist/installers/ --arch amd64

Error: Error executing command (2): 
fakeroot dpkg-deb --build /tmp/electron-117431-32043-5z1q70.lu6oe0zfr/Unity_1.0.0_amd64
dpkg-deb: error: parsing file '/tmp/electron-117431-32043-5z1q70.lu6oe0zfr/Unity_1.0.0_amd64/DEBIAN/control' near line 11 package 'unity':
 blank line in value of field 'Homepage'

    at ChildProcess.<anonymous> (/home/krdsjenitha/Desktop/electron/track-work/node_modules/electron-installer-debian/src/installer.js:67:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12) 'Error: Error executing command (2): \nfakeroot dpkg-deb --build /tmp/electron-117431-32043-5z1q70.lu6oe0zfr/Unity_1.0.0_amd64\ndpkg-deb: error: parsing file \'/tmp/electron-117431-32043-5z1q70.lu6oe0zfr/Unity_1.0.0_amd64/DEBIAN/control\' near line 11 package \'unity\':\n blank line in value of field \'Homepage\'\n\n    at ChildProcess.<anonymous> (/home/krdsjenitha/Desktop/electron/track-work/node_modules/electron-installer-debian/src/installer.js:67:23)\n    at emitTwo (events.js:106:13)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:885:16)\n    at Socket.<anonymous> (internal/child_process.js:334:11)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at Pipe._handle.close [as _onclose] (net.js:501:12)'

**Comment by prasadbe** [comment]
Update Please ?

**Comment by prasadbe** [comment]
It is happen due to description  empty in package.json .Once I added content it works

Thank You

**Comment by unindented** [comment]
Ah, sorry I couldn't help you, but glad you found the issue.
